project:
  type: website

website:
  title: "Deep Learning Exploration"
  favicon: assets/favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Projects"
        menu:
          - text: "Painting Classifier"
            href: projects/painting-classifier.qmd
          - text: "CIFAR Image Classifier"
            href: projects/cifar-classifier.qmd
          - text: "QuickDraw Shape Recognition"
            href: projects/quickdraw-shapes.qmd
      - href: my-blog/index.qmd
        text: Blog/Notebooks
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: true