---
title: "Deep Learning Exploration"
---

Welcome to my primary AI/ML live portfolio, Deep Learning Exploration! This is a website showcasing my interactive AI projects, along with Jupyter Notebooks and blog entries so you can get an idea for the process/code behind the projects. This site is actively in development, and I'm working on new models and projects - most of which will be embedded here from HuggingFace or a similar area.

Use the links along the top menu to learn more and experiment with some of the models I'm working on. A dedicated blog on this site is also coming soon, where you can view Jupyter Notebooks and look at the insides of these models. The code for many of the models on this site comes from my [corresponding GitHub repository](https://github.com/PontiacGTO2006/quarto-dl-site).

## Projects/content on this site
* **[Ashryver Deep Learning Classifiers](projects/painting-classifier.qmd)** - these are painting classifiers that I'm currently working on, **designed to classify works by 20-30 different arists**. Version 1 is currently live; I'm considering releasing a future v2. *[Why is it called Ashryver?](https://discordantharmony.com/2026/07/07/ashryver-v1-painting-classifier-release-summary/)*
* [CIFAR Image Classification Model](projects/cifar-classifier.qmd) - this a complete and working model which is able to **recognize images of everyday objects and output the correct classification**. It has been trained on 60,000 images from the CIFAR dataset of everyday objects, and can identify images of airplanes, cars, buildings, animals, and others.
* [QuickDraw Image Recognition Model](projects/quickdraw-shapes.qmd) - a **three-category live drawing recognizer** that classifies shapes into circle, square, and triangle. You draw into a live sketching area and the model outputs a realtime prediction.
* **Kaggle Competition notebooks** - these are Jupyter Notebooks I've created for a few of the introductory Kaggle competitions, some of which are incomplete. These will be coming soon on the blog.
* **Project details** available on the [blog](my-blog/index.qmd) (currently a WIP).

## Links to other resources
Here are some other places where I'm hosting or displaying AI/ML projects and content:

* [My primary portfolio website](https://discordantharmony.com/machine-learning-projects-ai-models/)
* [HuggingFace account with insane username](https://huggingface.co/DorianfirstmetAelinwh4-sEFOREBEEPBE)
* [GitHub Machine Learning repository](https://github.com/PontiacGTO2006/machine-learning)
* [GitHub FastAI Repository](https://github.com/PontiacGTO2006/fastai-course)

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.
